VERBOSE_HIGH = 3
VERBOSE_MEDIUM= 2
VERBOSE_LOW=1
VERBOSE_NONE = 0
METRICS_MAXIMIZE = 1
METRICS_MINIMIZE = 2

class ObjectiveTypeEnum(object):
    (INT, INTEGERFROMFLOAT, FLOAT, REALVALFORFLOAT) = range(0, 4)